#!/bin/sh

cd /src/

export DOORMAN_ENV=prod
export DOORMAN_SETTINGS=$PWD/settings.cfg

chpst -u doorman -U doorman /usr/bin/python manage.py db upgrade

exec chpst \
  -u doorman \
  -U doorman \
  gunicorn \
    --workers 4 \
    --bind 0.0.0.0:5000 \
    manage:app
